'use strict';
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8');
const icons=vm.runInNewContext('('+source.match(/const icons = (\{[\s\S]*?\n\});/)[1]+')');
const palette={background:'#141113',surface:'#211B1E',raised:'#2B2327',primary:'#8C2946',primaryPressed:'#A03555',accent:'#E9A0B5',text:'#F8F2F3',muted:'#C5B8BD',outline:'#5F4853',subtle:'#362B31',selected:'#4C2837',success:'#ACD3BE',successBg:'#24352C',warning:'#E4C295',warningBg:'#382E22',error:'#FFB4AB',errorBg:'#412B2C',cover:'#443039',coverLine:'#9D687D',vi:'#512D43',levi:'#303F3C',album:'#B9B076',albumBlue:'#8BABB1',albumPink:'#B78097'};
const styles={display:{size:30,line:36,weight:700},title:{size:24,line:30,weight:700},heading:{size:18,line:24,weight:700},body:{size:14,line:21,weight:400},bodyStrong:{size:14,line:21,weight:500},small:{size:12,line:18,weight:400},label:{size:12,line:16,weight:500},button:{size:14,line:20,weight:500},time:{size:24,line:30,weight:500},tiny:{size:11,line:16,weight:400}};
const T=(name,text,style='body',color='text',other={})=>({type:'text',name,text,style,color,...other});
const I=(name,size=22,color='muted')=>({type:'icon',name:`Icono / ${name}`,icon:name,w:size,h:size,color});
const V=(name,children=[],other={})=>({type:'frame',name,dir:'vertical',gap:12,w:'fill',children:children.filter(Boolean),...other});
const H=(name,children=[],other={})=>({type:'frame',name,dir:'horizontal',gap:12,align:'center',w:'fill',children:children.filter(Boolean),...other});
const R=(name,w,h,bg='subtle',radius=0)=>({type:'rect',name,w,h,bg,radius});
const C=(key,overrides={},other={})=>({type:'instance',name:key,component:key,overrides,...other});
const A=(n,to)=>({...n,to});
const spacer=(h=8)=>R('Separación',1,h,'transparent');
const line=()=>R('Separador','fill',1);
const TEXT_BUTTON=(label,to,icon)=>A(H(label,[icon?I(icon,18,'accent'):null,T('Etiqueta',label,'label','accent')],{w:'hug',h:48,gap:6}),to);
const ICON_BUTTON=(icon,to,label)=>A(H(label||icon,[I(icon)],{w:48,h:48,justify:'center',radius:24}),to);
const button=(label,to,kind='primary',icon)=>A(C(`Button/${kind}`,{'Label':label},{w:'fill',...(icon?{unusedIcon:icon}:{})}),to);
const input=(label,value,to,kind='default',helper)=>V(`Campo / ${label}`,[T('Etiqueta',label,'label'),A(C(`Input/${kind}`,{Value:value},{w:'fill'}),to),helper?T('Ayuda',helper,'small','muted'):null],{gap:8});
const search=(placeholder,to)=>A(C('Search',{'Placeholder':placeholder},{w:'fill'}),to);
const chip=(label,selected,to)=>A(C(`Chip/${selected?'selected':'default'}`,{Label:label}),to);
const status=(value)=>C(`Status/${value}`);
const note=(text,tone='info')=>H(`Aviso / ${tone}`,[I(tone==='error'?'info':'info',18,tone==='error'?'error':'accent'),T('Mensaje',text,'small',tone==='error'?'error':'muted',{w:'fill'})],{padding:12,gap:10,bg:tone==='error'?'errorBg':'raised',radius:12,align:'start'});
const section=(title,link)=>H(title,[T('Título de sección',title,'bodyStrong','text',{w:'fill'}),link],{gap:8});
const cover=(initials='GR',h=128,other={})=>C(other.compact?'CoverCompact':'Cover',{Initials:initials},{w:'fill',h,...other});
const album=(name='run')=>C(`Album/${name}`,{},{});
const songs={started:{title:"Let's Get It Started",artist:'The Black Eyed Peas',duration:'03:37',album:'started'},enemy:{title:'Enemy',artist:'Imagine Dragons & JID',duration:'02:53',album:'enemy'},run:{title:'Run Boy Run',artist:'Woodkid',duration:'03:33',album:'run'},after:{title:'After Dark',artist:'Mr.Kitty',duration:'04:17',album:'enemy'}};
const people={geralt:{name:'Geralt de Rivia',work:'The Witcher 3: Wild Hunt',initials:'GR',status:'editing',song:'Run Boy Run'},vi:{name:'Vi',work:'Arcane',initials:'Vi',status:'pending',song:'Enemy'},levi:{name:'Levi Ackerman',work:'Attack on Titan',initials:'LA',status:'idea',song:'Canción por elegir'}};
const project=(id,to='detail-editing',override={})=>{const p={...people[id],...override};return A(C('ProjectRow',{Name:p.name,Work:p.work,Song:p.song,Initials:p.initials,State:p.status},{w:'fill'}),to);};
const songRow=(id,to='clip',playTo='clip-playing')=>{const s=songs[id];return H(`Canción / ${s.title}`,[A(H('Seleccionar canción',[album(s.album),V('Datos de canción',[T('Título',s.title,'bodyStrong'),T('Artista',s.artist,'small','muted'),T('Versión',`Estudio · ${s.duration}`,'tiny','muted')],{gap:2,w:'fill'})],{w:'fill'}),to),ICON_BUTTON('play',playTo,`Escuchar ${s.title}`)],{padding:[12,0],gap:8});};
const navigation=(active)=>C(`Navigation/${active}`,{},{w:'fill'});
const statusbar=()=>C('System/Status',{}, {w:'fill'});
const gesture=()=>C('System/Gesture',{}, {w:'fill'});
const top=(title,subtitle,back)=>back?H('Cabecera contextual',[ICON_BUTTON('back',back,'Volver'),T('Título',title,'heading','text',{w:'fill'})],{padding:[4,12],h:60,gap:4}):H('Cabecera principal',[V('Encabezado',[T('Título',title,'display'),subtitle?T('Subtítulo',subtitle,'small','muted'):null],{gap:4,w:'fill'}),ICON_BUTTON('settings','settings','Ajustes')],{padding:[12,20,16,20],gap:8});
const page=(id,name,{title,subtitle,back,body=[],footer=[],nav=null,group='Principales',description='',dialog=false})=>({id,name,group,description,dialog,node:V(name,[statusbar(),top(title,subtitle,back),V('Contenido desplazable',body,{gap:16,padding:[0,20,20,20],w:'fill',h:'fill',clip:true,scroll:true}),footer.length?V('Acciones',footer,{padding:[12,20],gap:8,bg:'background'}):null,nav?navigation(nav):null,gesture()],{w:412,h:892,bg:'background',gap:0,clip:true,radius:24})});
const components={};
for(const kind of ['primary','secondary','disabled','danger'])components[`Button/${kind}`]=H(`Button/${kind}`,[T('Label','Guardar','button',kind==='disabled'?'muted':kind==='danger'?'error':'text',{prop:'Label'})],{w:372,h:52,justify:'center',padding:[12,16],radius:14,bg:kind==='primary'?'primary':kind==='disabled'?'raised':kind==='danger'?'errorBg':'surface',stroke:kind==='secondary'?'outline':null,description:'Acción de 52 px. Cambia Label desde las propiedades de la instancia.'});
for(const kind of ['default','error','focused'])components[`Input/${kind}`]=H(`Input/${kind}`,[T('Value','Texto del campo','body','text',{prop:'Value',w:'fill'})],{w:372,h:52,padding:[12,14],radius:12,bg:'surface',stroke:kind==='error'?'error':kind==='focused'?'accent':'outline'});
components.Search=H('Search',[I('search',20),T('Placeholder','Personaje, obra o canción','body','muted',{prop:'Placeholder',w:'fill'})],{w:372,h:52,padding:[12,14],bg:'surface',stroke:'outline',radius:12,gap:10});
for(const state of ['default','selected'])components[`Chip/${state}`]=H(`Chip/${state}`,[T('Label','Todos','label',state==='selected'?'text':'muted',{prop:'Label'})],{w:'hug',h:48,padding:[12,14],radius:24,bg:state==='selected'?'selected':'transparent',stroke:state==='selected'?'accent':'outline',gap:0});
for(const [key,title,ic,col,bg] of [['idea','Idea','idea','muted','raised'],['pending','Pendiente','clock','warning','warningBg'],['editing','En edición','edit','accent','selected'],['done','Terminado','check','success','successBg']])components[`Status/${key}`]=H(`Status/${key}`,[I(ic,14,col),T('Label',title,'label',col)],{w:'hug',h:28,padding:[6,8],gap:6,bg,radius:8});
components.Cover=V('Cover',[{type:'art',name:'Decoración / intervalos',w:'fill',h:'fill'},T('Initials','GR','display','text',{prop:'Initials',size:76,line:84,absolute:true,x:228,y:48,w:132,constraints:{horizontal:'MAX',vertical:'MAX'}}),T('Imagen sustituible','Imagen del personaje','tiny','text',{absolute:true,x:12,y:104,constraints:{horizontal:'MIN',vertical:'MAX'}})],{w:372,h:128,bg:'cover',radius:14,clip:true,description:'Marcador visual editable. Sustituye el relleno por la imagen real del personaje y oculta Initials y Decoración.'});
// Geometry belongs to the masters. Figma instances inherit it through constraints.
components.CoverCompact=V('CoverCompact',[{type:'art',name:'Decoración / intervalos',w:'fill',h:'fill'},T('Initials','GR','display','text',{prop:'Initials',size:30,line:36,absolute:true,x:4,y:40,w:52,constraints:{horizontal:'MAX',vertical:'MAX'}})],{w:60,h:76,bg:'cover',radius:14,clip:true,description:'Portada compacta. Cambia Initials o la imagen; la posición se hereda del componente.'});
for(const [id,bg] of [['started','album'],['run','albumBlue'],['enemy','albumPink']])components[`Album/${id}`]=H(`Album/${id}`,[I('music',24,'background')],{w:52,h:52,bg,justify:'center',radius:10});
components.ProjectRow=H('ProjectRow',[C('CoverCompact',{Initials:'GR'},{w:60,h:76}),V('Información',[T('Name','Geralt de Rivia','bodyStrong','text',{prop:'Name'}),T('Work','The Witcher 3: Wild Hunt','small','muted',{prop:'Work'}),T('Song','Run Boy Run','small','muted',{prop:'Song'}),C('Status/editing',{},{slot:'State'})],{w:'fill',gap:3}),I('chevron',18,'muted')],{w:372,padding:[12,0],gap:12});
for(const active of ['projects','music','history'])components[`Navigation/${active}`]=H(`Navigation/${active}`,[['projects','Proyectos','projects','home'],['music','Música','music','music'],['history','Historial','history','history']].map(([key,label,ic,to])=>A(V(`Destino / ${label}`,[H('Indicador',[I(ic,22,key===active?'text':'muted')],{w:64,h:32,bg:key===active?'selected':'transparent',radius:20,justify:'center'}),T('Etiqueta',label,'label',key===active?'text':'muted',{alignText:'center'})],{w:'fill',h:60,align:'center',gap:4}),to)),{w:412,h:76,padding:[8,12],gap:0,bg:'surface'});
components['System/Status']=H('System/Status',[T('Hora','9:41','label','text'),R('Espacio','fill',1,'transparent'),T('Indicadores','▴  ◔  ▰','small','text')],{w:412,h:32,padding:[8,24],gap:0});
components['System/Gesture']=H('System/Gesture',[R('Indicador de gesto',108,4,'muted',4)],{w:412,h:24,justify:'center'});
const filters=(selected='all')=>H('Filtros de estado',[chip('Todos',selected==='all','home'),chip('Ideas',selected==='ideas','home-ideas'),chip('Pendientes',selected==='pending','home-pending'),chip('En edición',selected==='editing','home-editing')],{gap:6});
const feature=()=>A(V('AMV destacado',[cover('GR',124),V('Contenido de tarjeta',[H('Personaje y estado',[V('Identidad',[T('Nombre','Geralt de Rivia','title'),T('Obra','The Witcher 3: Wild Hunt','small','muted')],{w:'fill',gap:3})],{gap:0}),status('editing'),line(),H('Música y fragmento',[I('music',18,'accent'),T('Canción','Run Boy Run','small','text',{w:'fill'}),T('Fragmento','00:26','label','accent')],{gap:8})],{padding:[0,16,16,16],gap:10})],{bg:'surface',stroke:'outline',radius:20,gap:14}),'detail-editing');
const blank=(title,body,cta)=>V('Estado vacío',[H('Símbolo',[I('idea',32,'accent')],{w:76,h:76,bg:'selected',justify:'center',radius:24}),T('Título',title,'title','text',{alignText:'center'}),T('Descripción',body,'body','muted',{alignText:'center',w:'fill'}),cta],{align:'center',padding:[40,12],gap:16});
const screens=[];
screens.push(page('home','01 · Proyectos',{title:'Proyectos',subtitle:'3 ideas en movimiento',body:[search('Personaje, obra o canción','home-ideas'),filters(),section('Retoma tu edición'),feature(),section('Lo siguiente'),project('vi','detail-idea'),line(),project('levi','detail-idea')],footer:[button('＋  Nuevo AMV','new')],nav:'projects',description:'Punto de entrada. La edición activa se prioriza; el resto mantiene una lista legible.'}));
for(const [id,sel,title,p] of [['home-ideas','ideas','Tus ideas','levi'],['home-pending','pending','Pendientes','vi'],['home-editing','editing','En edición','geralt']])screens.push(page(id,`02 · Proyectos / ${title}`,{title:'Proyectos',subtitle:'Encuentra tu siguiente montaje',body:[search('Personaje, obra o canción','home-empty'),filters(sel),section(title),project(p,p==='geralt'?'detail-editing':'detail-idea')],footer:[button('＋  Nuevo AMV','new')],nav:'projects',group:'Estados',description:'Filtro aplicado. La navegación y el botón de crear conservan su posición.'}));
screens.push(page('home-empty','03 · Proyectos / vacío',{title:'Proyectos',subtitle:'Tu próximo AMV empieza aquí',body:[blank('Una idea es suficiente','Escribe un personaje y guarda lo que te gustaría crear. La canción puede llegar después.')],footer:[button('Crear mi primer AMV','new')],nav:'projects',group:'Estados'}));
const characterSearch=(value='Personaje y obra')=>V('Buscar personaje',[T('Pregunta','¿A quién le dedicas este AMV?','bodyStrong'),H('Entrada y búsqueda',[A(C('Input/focused',{Value:value},{w:'fill'}),'new-found'),A(H('Buscar personaje',[I('search',22,'text')],{w:52,h:52,bg:'primary',radius:12,justify:'center'}),'new-loading')],{gap:8}),T('Ayuda','Nombre y serie, película, anime o videojuego.','small','muted')],{gap:8});
const characterCard=(editable=false)=>V('Personaje encontrado',[cover('GR',112),H('Identidad encontrada',[H('Resultado',[I('check',16,'success'),T('Mensaje','Personaje encontrado','label','success')],{w:'fill',gap:6}),TEXT_BUTTON('Cambiar imagen','image-chooser')],{gap:4}),input('Nombre','Geralt de Rivia',editable?'new-manual':null),input('Obra','The Witcher 3: Wild Hunt',editable?'new-manual':null)],{padding:14,bg:'surface',stroke:'outline',radius:16,gap:10});
screens.push(page('new','04 · Nuevo AMV / inicio',{title:'Nuevo AMV',back:'home',body:[T('Introducción','Todo empieza por un personaje.','title'),T('Contexto','Busca a quien tienes en mente. Completaremos su ficha aquí mismo.','body','muted'),characterSearch(),note('Podrás cambiar el nombre, la obra y la imagen.'),TEXT_BUTTON('Escribir los datos manualmente','new-manual'),input('Idea para el montaje (opcional)','Una escena, una emoción, un momento…')],footer:[button('Guardar idea',null,'disabled')],description:'La búsqueda completa el propio formulario, sin selector ni confirmación obligatorios.'}));
screens.push({...page('new-loading','05 · Nuevo AMV / buscando',{title:'Nuevo AMV',back:'new',body:[characterSearch('Geralt de The Witcher 3'),V('Carga',[R('Marcador de imagen','fill',112,'raised',14),R('Marcador de nombre',240,18,'raised',6),R('Marcador de obra',180,14,'raised',6),T('Estado','Buscando personaje e imagen…','body','muted')],{padding:16,bg:'surface',radius:16})],footer:[button('Guardar idea',null,'disabled')],group:'Estados'}),autoTo:'new-found'});
screens.push(page('new-found','06 · Nuevo AMV / autocompletado',{title:'Nuevo AMV',back:'new',body:[characterSearch('Geralt de The Witcher 3'),characterCard(true),input('Idea para el montaje (opcional)','La calma antes del combate…'),T('Guardado','Se guardará como Idea. Añade la canción cuando quieras.','small','muted')],footer:[button('Guardar idea','detail-idea')],description:'Datos e imagen visibles de inmediato. El usuario solo guarda su AMV.'}));
screens.push(page('new-manual','07 · Nuevo AMV / entrada manual',{title:'Nuevo AMV',back:'new',body:[note('No hemos encontrado una coincidencia clara. Puedes completar la ficha.'),A(V('Añadir imagen',[I('image',32,'accent'),T('Etiqueta','Añadir imagen','bodyStrong'),T('Opcional','Opcional','small','muted')],{h:140,align:'center',justify:'center',bg:'surface',stroke:'outline',radius:16}),'image-chooser'),input('Nombre del personaje','Escribe su nombre','new-found'),input('Obra (opcional)','Serie, película, anime o juego'),input('Idea para el montaje (opcional)','¿Qué te gustaría contar?')],footer:[button('Guardar idea','detail-idea')],group:'Estados'}));
screens.push(page('new-ambiguous','08 · Personaje / precisar obra',{title:'Precisar personaje',back:'new',body:[T('Título','Hay varios personajes con ese nombre.','title'),T('Mensaje','Añade la obra o elige la versión que tienes en mente.','body','muted'),input('Personaje y obra','Joker de…','new-found'),A(V('Candidato / cine',[cover('J',100),T('Nombre','Joker','heading'),T('Obra','Joker · película de 2019','small','muted')],{padding:14,bg:'surface',radius:16}),'new-found'),A(V('Candidato / videojuego',[cover('J',100),T('Nombre','Joker','heading'),T('Obra','Persona 5 · videojuego','small','muted')],{padding:14,bg:'surface',radius:16}),'new-found')],group:'Estados',description:'Solo se pide precisión cuando la identidad o adaptación es ambigua. Las tarjetas son ejemplos visuales.'}));
screens.push(page('image-chooser','09 · Cambiar imagen',{title:'Imagen del personaje',back:'new-found',body:[T('Título','Elige cómo recordarlo.','title'),T('Ayuda','La imagen debe corresponder al personaje y a la versión de su obra.','body','muted'),cover('GR',220),T('Fuente','Imagen provisional · Sustituir por la fuente elegida','small','muted'),H('Imágenes candidatas',[A(cover('GR',96,{w:'fill',compact:true}),'new-found'),A(cover('GR',96,{w:'fill',compact:true}),'new-found')],{gap:12}),button('Elegir una imagen del dispositivo','new-found','secondary')],footer:[button('Usar esta imagen','new-found')],group:'Secundarias'}));
function detail(id,state){const done=state==='done',idea=state==='idea';return page(id,`10 · Detalle / ${state}`,{title:'Tu AMV',back:done?'history':'home',body:[cover('GR',144),H('Personaje',[V('Identidad',[T('Nombre','Geralt de Rivia','display'),T('Obra','The Witcher 3: Wild Hunt','body','muted')],{w:'fill',gap:4}),ICON_BUTTON('edit','edit-character','Editar personaje')]),H('Estado del proyecto',[T('Etiqueta','Estado del proyecto','label','muted',{w:'fill'}),A(status(state),'status-sheet')]),line(),section('La banda sonora',idea?null:TEXT_BUTTON('Cambiar','music-results')),idea?A(V('Sin canción',[I('plus',26,'accent'),T('Título','Añadir una canción','heading'),T('Ayuda','Encuentra el sonido de este AMV.','small','muted')],{padding:18,bg:'surface',stroke:'outline',radius:16}),'music-results'):V('Canción elegida',[H('Datos de canción',[album('run'),V('Datos',[T('Título','Run Boy Run','bodyStrong'),T('Artista','Woodkid','small','muted')],{gap:3,w:'fill'})]),line(),H('Selección',[V('Tiempos',[T('Duración','Tu fragmento · 26 s','small','muted'),T('Intervalo','00:42 — 01:08','heading')],{w:'fill',gap:3}),TEXT_BUTTON('Ajustar','clip','cut')])],{padding:16,bg:'surface',stroke:'outline',radius:16,gap:12}),section('Notas del montaje',TEXT_BUTTON('Editar','edit-character')),V('Notas',[T('Contenido','Empezar con planos tranquilos. Reservar el combate para la subida de la canción.','body','muted')],{padding:14,bg:'surface',radius:12}),TEXT_BUTTON('Eliminar proyecto','delete-dialog')],footer:[button(done?'Reabrir proyecto':'Marcar como terminado',done?'detail-editing':'history','secondary')],description:'Texto editable, estado visible y decisiones musicales en un mismo lugar.'});}
screens.push(detail('detail-idea','idea'),detail('detail-editing','editing'),detail('detail-done','done'));
screens.push(page('edit-character','11 · Editar personaje',{title:'Editar personaje',back:'detail-editing',body:[characterCard(true),input('Notas del montaje','Empezar con planos tranquilos…'),T('Ayuda','La canción y el fragmento se conservan al cambiar estos datos.','small','muted')],footer:[button('Guardar cambios','detail-editing')],group:'Secundarias'}));
screens.push(page('music','12 · Música',{title:'Música',subtitle:'Una canción puede ser el principio',body:[search('Título o artista','music-results'),section('Para tus próximos AMV'),songRow('started','assign'),line(),songRow('enemy','assign'),line(),songRow('run','assign'),line(),songRow('after','assign'),note('Escucha una canción y elige el AMV al que quieres añadirla.')],nav:'music'}));
screens.push(page('music-results','13 · Buscar canción / resultados',{title:'Elegir canción',back:'detail-idea',body:[H('Contexto',[I('user',18,'accent'),T('Proyecto','Para Geralt de Rivia','small','muted')],{padding:12,bg:'surface',radius:10}),search('Woodkid','music-empty'),section('Resultados'),songRow('run'),T('Fuente','Fuente de reproducción por confirmar','small','muted'),note('Los tiempos se asociarán a esta versión concreta de la canción.')],description:'Elegir el resultado asigna la canción y abre el selector de fragmento.'}));
screens.push(page('music-empty','14 · Buscar canción / sin resultados',{title:'Elegir canción',back:'music-results',body:[search('Título o artista','music-results'),blank('No encontramos esa canción','Prueba con el título completo o con el nombre del artista.',button('Cambiar búsqueda','music-results','secondary'))],group:'Estados'}));
screens.push(page('assign','15 · Asignar canción a un AMV',{title:'Añadir a un AMV',back:'music',body:[T('Título','¿A qué proyecto le va esta canción?','title'),H('Canción elegida',[album('run'),V('Datos',[T('Título','Run Boy Run','bodyStrong'),T('Artista','Woodkid','small','muted')],{gap:3})],{padding:14,bg:'surface',radius:14}),project('geralt','clip'),line(),project('vi','clip'),line(),project('levi','clip')],group:'Secundarias'}));
const player=(playing=false,unavailable=false)=>V('Reproductor online',[T('Canción','Run Boy Run','title'),T('Artista','Woodkid','small','muted'),H('Control',[ICON_BUTTON(unavailable?'info':playing?'pause':'play',unavailable?null:playing?'clip':'clip-playing',unavailable?'Fuente no disponible':'Reproducción')],{w:'fill',justify:'center',h:60}),H('Información',[T('Tipo',unavailable?'Fuente no disponible':'Reproductor online','tiny','muted',{w:'fill'}),T('Tiempo',playing?'00:51 / 03:33':'00:42 / 03:33','tiny','text')],{gap:6})],{padding:16,bg:'selected',stroke:'outline',radius:16,h:204,gap:5});
const timeline=()=>V('Línea temporal',[{type:'timeline',name:'Selección de 00:42 a 01:08',w:'fill',h:32,start:42,end:68,duration:213},H('Escala',[T('Inicio','00:00','tiny','muted'),R('Espacio','fill',1,'transparent'),T('Medio','01:46','tiny','muted'),R('Espacio','fill',1,'transparent'),T('Final','03:33','tiny','muted')],{gap:0})],{gap:2});
const timeField=(label,value,to,error=false)=>V(label,[T('Etiqueta',label,'label'),A(H('Tiempo',[T('Valor',value,'time')],{h:56,w:'fill',justify:'center',bg:'surface',stroke:error?'error':'outline',radius:12}),to),{type:'slider',name:`Ajustar ${label.toLowerCase()}`,w:'fill',h:48,progress:label==='Inicio'?.2:.32,to}],{w:'fill',gap:7});
function clip(id,mode='normal'){const invalid=mode==='invalid',playing=mode==='playing';return page(id,`16 · Fragmento / ${mode}`,{title:'Tu fragmento',back:'detail-editing',body:[player(playing),H('Reproducción',[ICON_BUTTON('arrowleft','clip','Retroceder cinco segundos'),T('Posición',playing?'00:51 / 03:33':'00:42 / 03:33','small','muted',{w:'fill',alignText:'center'}),ICON_BUTTON('arrowright','clip-playing','Avanzar cinco segundos')],{gap:6}),section('Quédate con ese momento'),timeline(),H('Puntos de corte',[timeField('Inicio','00:42','clip-invalid',invalid),timeField('Final',invalid?'00:30':'01:08','clip',invalid)],{gap:12,align:'start'}),invalid?note('El final debe estar después del inicio.','error'):H('Duración',[T('Etiqueta','Duración del fragmento','small','muted',{w:'fill'}),T('Duración','26 segundos','heading','accent')],{padding:14,bg:'surface',radius:12}),T('Ayuda','Guardamos los tiempos y la referencia. No se descarga ningún archivo.','small','muted')],footer:[H('Acciones de selección',[button(playing?'Pausar':'Probar',playing?'clip':'clip-playing','secondary'),button('Guardar fragmento',invalid?null:'detail-editing',invalid?'disabled':'primary')],{gap:10})],group:mode==='normal'?'Principales':'Estados',description:'El intervalo se guarda como marcas. No se representa una onda de audio ficticia ni una exportación no autorizada.'});}
screens.push(clip('clip'),clip('clip-playing','playing'),clip('clip-invalid','invalid'));
screens.push(page('clip-unavailable','17 · Fragmento / fuente no disponible',{title:'Tu fragmento',back:'detail-editing',body:[player(false,true),note('Esta versión ya no puede reproducirse. Tu proyecto y sus marcas siguen guardados.','error'),T('Título','Tu selección sigue aquí','heading'),H('Fragmento',[T('Tiempos','00:42 — 01:08','time'),T('Duración','26 s','small','muted')]),T('Ayuda','Si eliges otra versión, revisa los tiempos: puede tener una introducción diferente.','body','muted')],footer:[button('Buscar otra versión','music-results'),button('Volver al proyecto','detail-editing','secondary')],group:'Estados'}));
screens.push(page('history','18 · Historial',{title:'Historial',subtitle:'Cada idea que llegó a ser un AMV',body:[search('Buscar un AMV terminado','history-empty'),section('Terminados'),project('geralt','detail-done',{status:'done',song:'Run Boy Run'}),T('Fecha','Finalizado el 8 de septiembre de 2026','small','muted'),note('Tus canciones, fragmentos y notas se conservan. Puedes reabrir cualquier proyecto.')],nav:'history'}));
screens.push(page('history-empty','19 · Historial / vacío',{title:'Historial',subtitle:'Cada idea que llegó a ser un AMV',body:[blank('Aquí estarán tus AMV terminados','Cuando termines un proyecto, aparecerá aquí con su canción, fragmento y notas.',button('Volver a Proyectos','home','secondary'))],nav:'history',group:'Estados'}));
const setting=(ic,label,value,to)=>A(H(`Ajuste / ${label}`,[I(ic,22,'accent'),V('Información',[T('Nombre',label,'bodyStrong'),T('Valor',value,'small','muted')],{w:'fill',gap:4}),to?I('chevron',18):null],{padding:[14,0]}),to);
screens.push(page('settings','20 · Ajustes',{title:'Ajustes',back:'home',body:[section('Tu espacio de trabajo'),setting('image','Apariencia','Oscura · Identidad granate'),line(),setting('lock','Tus proyectos','Guardados en este dispositivo'),line(),setting('music','Reproducción','Por Internet · Según disponibilidad'),line(),section('Acerca de AMV Manager'),T('Descripción','Un espacio para guardar ideas, organizar tus montajes y recordar el fragmento perfecto.','body','muted'),note('La búsqueda de personajes se apoya en fuentes de Internet. Siempre puedes escribir los datos manualmente.'),T('Versión','Propuesta de interfaz · v0.2','small','muted')],group:'Secundarias',description:'Ajustes del producto. Las herramientas para restablecer datos de demostración se eliminan de la interfaz final.'}));
screens.push(page('status-sheet','21 · Cambiar estado',{title:'Estado del proyecto',back:'detail-editing',body:[T('Título','¿En qué punto está tu AMV?','title'),...Object.entries({idea:['Idea','Se me ha ocurrido y quiero guardarlo.','detail-idea'],pending:['Pendiente','He decidido hacerlo.','home-pending'],editing:['En edición','Estoy trabajando en el montaje.','detail-editing'],done:['Terminado','Ya está hecho. Guardarlo en Historial.','history']}).map(([s,[title,desc,to]])=>A(H(`Estado / ${title}`,[status(s),T('Descripción',desc,'small','muted',{w:'fill'})],{padding:16,bg:s==='editing'?'selected':'surface',stroke:s==='editing'?'accent':'outline',radius:14,align:'center'}),to))],group:'Secundarias'}));
screens.push(page('delete-dialog','22 · Eliminar proyecto',{title:'Eliminar proyecto',back:'detail-editing',body:[spacer(40),V('Confirmación',[I('info',32,'error'),T('Título','¿Eliminar este AMV?','title'),T('Descripción','Se eliminarán el proyecto, sus notas y las marcas del fragmento. La canción original no se modifica.','body','muted'),button('Conservar proyecto','detail-editing','secondary'),button('Eliminar proyecto','home','danger')],{padding:24,bg:'surface',radius:20,gap:20})],group:'Estados',description:'Confirmación para la acción destructiva. En producción se añadirá Deshacer.'}));

module.exports={version:'0.2.2',targetFile:'TNlwUUcaNqk7BdJCu2EDtJ',pageName:'AMV · Interfaces refinadas v0.2.2',font:'Roboto',palette,styles,icons,components,screens,notes:[
  'Los marcos son editables: Auto Layout, variables de color y espaciado, estilos de texto e instancias de componentes.',
  'Las imágenes son marcadores provisionales del prototipo original. Sustituir por imágenes de fuentes verificadas; no se han inventado resultados de una búsqueda.',
  'El prototipo de Figma enlaza estados predefinidos. No consulta IA, no reproduce audio ni escribe datos de proyectos.',
  'Tipografía refinada a Roboto para alinearse con Android. La maqueta HTML inicial usaba Segoe UI y Bahnschrift.',
  'El importador crea una página nueva. No elimina ni modifica los diseños ya existentes. Ejecutarlo otra vez conserva el diseño importado en vez de sobrescribir tus cambios.',
]};
